name: pymc3_examples
channels:
- defaults
# - conda-forge
dependencies:
- python==3.6.*
- cython
- ipython
- jupyter
- jupyterlab
- ipywidgets
- mkl
- mkl-service
- numpy
- scipy
- matplotlib
- pandas
- pyarrow
- scikit-learn
- seaborn
- patsy
- statsmodels
- python-graphviz
- pytest
- nose
- parameterized
- tqdm
- watermark
- sphinx
- nbsphinx
- numpydoc
- recommonmark
- pip
